### PR TITLE
Support dynamic rendering for github projects

### PR DESCRIPTION
**Pull request by al3xnag**
Hello!

What do you think about reading ember, ember-data or ember-cli version from package.json or bower.json and rendering it on the badge?

Examples:
https://embadge.io/v1/github_username/github_repo/master/ember.svg
https://embadge.io/v1/github_username/github_repo/develop/ember-data.svg
https://embadge.io/v1/github_username/github_repo/develop/ember-cli.svg?label=EmberCLI

Update:
I deployed it on heroku, see working examples:
https://salty-wildwood-27352.herokuapp.com/v1/Flexberry/ember-flexberry/master/ember.svg
https://salty-wildwood-27352.herokuapp.com/v1/Flexberry/ember-flexberry/develop/ember-data.svg
https://salty-wildwood-27352.herokuapp.com/v1/Flexberry/ember-flexberry/develop/ember-cli.svg?label=EmberCLI

### CODE REVIEW

**Comment by halfdan** [comment]
@nagits That's a brilliant idea! I'm currently working on an update to introduce a community feature. With your current implementation I'm worried about caching (sending off a request every time the endpoint is hit is a bit of a performance drag). 

The best solution here would probably be a webhook that forces the app to refetch package.json and render out the svg(s) as a static files - this way, after the first request it will simply serve a static file. I'll add that to the list. Thanks for the great demo!

**Comment by al3xnag** [comment]
I will look forward this feature :+1:.

**Comment by halfdan** [comment]
@nagits It is deployed btw. :)

**Comment by al3xnag** [comment]
@halfdan Awesome! Thanks!

**Pull request closed without merging**
